name: example
description: PausableBehaviorSubject example

version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  pausable_behavior_subject:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

publish_to: none